initial test implementation of gpu capable aces with changes to makefiles and autoconf to compile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS FC FCFLAGS LDFLAGS ac_ct_FC EXEEXT OBJEXT CC CFLAGS CPPFLAGS ac_ct_CC CXX CXXFLAGS ac_ct_CXX SIAL_COMPILER_LIBS ACESLIBS ACESFLAGS MKLLIBS MKLFLAGS SERIAL_CPP CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS FC FCFLAGS LDFLAGS ac_ct_FC EXEEXT OBJEXT CC CFLAGS CPPFLAGS ac_ct_CC CXX CXXFLAGS ac_ct_CXX SIAL_COMPILER_LIBS ACESLIBS ACESFLAGS MKLLIBS MKLFLAGS SERIAL_CPP CUDAPATH CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2627,8 +2627,18 @@ fi
 
 
 
+
+
+
 #This specifies the default C++ compiler in case no other compiler is found
 SERIAL_CPP="g++"
+
+#Settings for NVIDIA CUDA compiler and libraries
+if test x$CUDAPATH = x; then
+   { { echo "$as_me:$LINENO: error: Please specify the CUDA install path in variable CUDAPATH" >&5
+echo "$as_me: error: Please specify the CUDA install path in variable CUDAPATH" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 #Settings for Intel MKL libraries on linux machine
 # Check whether --enable-mkl or --disable-mkl was given.
@@ -2650,7 +2660,7 @@ fi
 SERIAL_CPP="icpc"
 #Also set SIAL_COMPILER_LIBS accordingly
 if test x$SIAL_COMPILER_LIBS = x; then
-SIAL_COMPILER_LIBS="-lsial -lsip_shared -laces2  -lifcore"
+SIAL_COMPILER_LIBS="-lsial -lsip_shared -laces2 -lifcore"
 fi
 ACESLIBS=$MKLLIBS
 ACESFLAGS=$MKLFLAGS
@@ -2697,8 +2707,8 @@ echo "$as_me: error: Please specify all the required libraries in variable CRAYL
 fi
 
 if test x$CRAYFLAGS = x; then
-   { { echo "$as_me:$LINENO: error: Please specify all the library locations in variable  CRAYFLAGS" >&5
-echo "$as_me: error: Please specify all the library locations in variable  CRAYFLAGS" >&2;}
+   { { echo "$as_me:$LINENO: error: Please specify all the library locations in variable CRAYFLAGS" >&5
+echo "$as_me: error: Please specify all the library locations in variable CRAYFLAGS" >&2;}
    { (exit 1); exit 1; }; }
 fi
 #Set c++ compiler
@@ -4047,6 +4057,7 @@ s,@ACESFLAGS@,$ACESFLAGS,;t t
 s,@MKLLIBS@,$MKLLIBS,;t t
 s,@MKLFLAGS@,$MKLFLAGS,;t t
 s,@SERIAL_CPP@,$SERIAL_CPP,;t t
+s,@CUDAPATH@,$CUDAPATH,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
